version: "3.3"

services:
  app_flap:
    container_name: app_flap
    build: .
    restart: always
    links:
      - pg_flap
    depends_on:
      - pg_flap
    ports:
      - 7777:7777
    environment:
      FLAP_DATABASE_HOST: pg_flap
      FLAP_DATABASE_PORT: 4444 #5432
      FLAP_DATABASE_USERNAME: guillermo
      FLAP_DATABASE_PASSWORD: 123456

    volumes:
      - .:/var/app/flap
    command: gunicorn --reload -b 0.0.0.0:7777 FlapWeb.wsgi

  pg_flap:
    container_name: pg_flap
    image: postgres:10.5
    restart: always
    ports:
      - 4444:4444 #5432:5432
    environment:
      POSTGRES_USER: guillermo
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/pg/data
    volumes:
      - ../pgdata:/var/pg/data