version: "3.3"

services:
  app_flap:
    container_name: app_flap
    build: .
    restart: always
    links:
      - pg_flap
    depends_on:
      - pg_flap
    ports:
      - 8000:8000
    environment:
      FLAP_DATABASE_HOST: pg_flap
      FLAP_DATABASE_PORT: 5432
      FLAP_DATABASE_USERNAME: guillermo
      FLAP_DATABASE_PASSWORD: 123456

    volumes:
      - .:/var/app/flap
    command: gunicorn -b :8000 FlapWeb.wsgi

  pg_flap:
    container_name: pg_flap
    image: postgres:10.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: guillermo
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/pg/data
    volumes:
      - ../pgdata:/var/pg/data

    # crear usuario y base de datos
    # createuser -s db_user_demo -P db_user_pass
    # psql -U db_user_demo
    # create database db_demo
