# Generated by Django 2.1.2 on 2018-11-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoadData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inducer',
            old_name='puchemid',
            new_name='pubchemid',
        ),
    ]
