# Generated by Django 2.1.2 on 2018-10-23 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoadData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('machine', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.FloatField()),
                ('time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('media', models.TextField()),
                ('strain', models.TextField()),
                ('IPTG', models.FloatField()),
                ('aTc', models.FloatField()),
                ('experiment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoadData.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoadData.Dna')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoadData.Sample')),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoadData.Sample'),
        ),
        migrations.AddField(
            model_name='construct',
            name='dna_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoadData.Dna'),
        ),
    ]
