# Generated by Django 2.1.2 on 2018-11-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoadData', '0002_loadprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadprocess',
            name='file',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
