# Generated by Django 2.1.2 on 2018-11-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoadData', '0002_auto_20181127_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inducer',
            old_name='sample_id',
            new_name='sample',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='sample_id',
            new_name='sample',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='experiment_id',
            new_name='experiment',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='dna_id',
            new_name='dna',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='sample_id',
            new_name='sample',
        ),
    ]
